# Generated by Django 5.1.4 on 2025-01-06 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Receita",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("descricao", models.TextField(default="Sem descrição")),
                ("ingredientes", models.TextField()),
                ("instrucoes", models.TextField()),
                ("modo_preparo", models.TextField(default="Sem infomação")),
                (
                    "prep_time",
                    models.IntegerField(help_text="Tempo de preparacao em minutos"),
                ),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
